#!/bin/sh
set -e -x

rm -f sed.???.eps

(
    set -e -x
    cat sed-input-header.tex
    ./compile-sed.py < sed1line-input.txt
    cat sed-input-trailer.tex
) > sed.tex

latex sed.tex
dvips -E -i -o sed. sed.dvi
for z in sed.00? ; do
    mv $z $z.eps
done


