=head1 NAME

makediary - output PostScript code for a paper diary.

=head1 SYNOPSIS

B<makediary --help>

B<makediary --version>

B<makediary> I<[options]>

=head1 DESCRIPTION

Prints PostScript code for a paper diary.  B<makediary> can generate
PostScript for several different paper sizes.  B<makediary> can include
events printed on dates specified in a F<.calendar> file.  The F<.calendar>
file is in the same format as used by pcal(1), with some extensions.

=head1 OPTIONS

=over

=item --address-pages=I<n>

Print I<n> address pages.  Defaults to 6.

=item --appointments

Print a column of appointment times on the right side of each day.

=item --appointment-width=I<N>[%]

Specify the width of the appointment times column as a percentage of the width
of the day.  Defaults to 35%.  The '%' sign is optional.  Implies
B<--appointments>.

=item --colour

When printing images, output colour PostScript.

=item --cover-image=I<imagefile>

Print I<imagefile> on the cover of the diary, centred and below the year.
The image will be scaled to fit inside a box across the page, and will replace
the smiley.

=item --day-to-page

Print one day to each page.  A year's worth of month calendars will be printed
across the bottom of each opening in the day pages.

=item --debug-boxes

Print dashed boxes around parts of the output for debugging the spacing.  These
parts include images, month calendars, and the drawing border of the whole page.

=item --debug-version

On the inside cover, print a page that describes the options that were used
to generate this diary, the usage message of the B<makediary>, and the CVS
version number.

=item --debug-whole-page-boxes

Around each diary page (not each sheet of paper), draw a faint box.

=item --eps-page=I<epsfilename>

Include a page whose content is I<epsfilename>, without a title or any other
decoration.  This could be useful for including maps, for instance.

=item --event-images

Print images next to events, where they are specified.  If this is not
specified, the events will be printed without images.

=item --help

Display a usage message and exit.

=item --image-page=IMAGEFILENAME[,title]

Display an image maximised onto a page.  This can be specified multiple times.
The images specified will be printed on consecutive pages immediately after the
personal information page.  The optional title will be used as the page title.

=item --image-2page=IMAGEFILENAME[,title]

Display an image maximised across two pages.  The optional title will be
printed on both pages.  A notes page will be inserted immediately before the
first page, if necessary, to ensure the image is printed on facing left and
right pages.

=item --line-spacing=I<d>

Make the line spacing on diary pages I<d> millimetres.  I<d> can be a
floating point number.

=item --moon

Print pictures of phases of the moon in the title of the day at each phase.

=item --northern-hemisphere-moon

Print pictures of phases of the moon as seen from the Northern Hemisphere,
instead of from the Southern Hemisphere.  Implies B<--mooon>.

=item --no-smiley

Don't print the smiley on the front cover.  The smiley also won't be printed if
a cover image is specified.

=item --notes-pages=I<n>

Print I<n> notes pages at the beginning and end of the diary.  Defaults to
6.

=item --output-file=I<filename>

Output PostScript code to I<filename>.  Defaults to F<diary.ps> if generating
PostScript, or F<diary.pdf> if generating PDF.  A lone 'B<->' means standard
output.

=item --page-size=I<size>

Specify the size of the pages.  This is not the same as the paper size, so
you can print smaller pages than the paper size.  See also the
B<--page-registration-marks> option.

=item --page-registration-marks

Print marks for cutting pages out of a sheet of paper.  This is useful when
printing pages that are smaller than the paper size.

=item --page-x-offset=I<x>

=item --page-y-offset=I<y>

Move each diary page this far on the paper.  The offsets are in
millimetres.  The rationale for these options is that printers tend not to
print exactly where told, so when printing double sided the pages on
opposite sides of the paper may not line up.  You can specify an offset to
make them line up.  I<x> and I<y> can be floating point numbers.

=item --paper-size=I<size>

Specify the size of the paper that you are printing on.  This is not the
same as the size of the diary pages.  Do B<makediary --help> for a list of
paper sizes.

=item --pdf

Generate PDF instead of PostScript.  Requires that ps2pdf be installed and in
your $PATH.  Untested on Windows.

=item --planner-years=I<n>

Print I<n> two-page planner years, starting with the diary year.  Defaults
to 2, ie the diary year and the following year.

=item --sh-ref

Print the Unix shell reference page.

=item --start-date=I<yyyy-mm-dd>

Start the diary on the specified date.  The date must be in yyyy-mm-dd
format.  If both B<--start-date> and B<--year> are both specified, the last
one specified will take precedence.

=item --units-ref

Print the Units reference page.

=item --unix-ref

Print the Unix commands reference page.

=item --version

Output version information and exit.

=item --vim-ref

Print the vi and vim reference pages.

=item --week-to-opening

Print a week to one opening.  This has, on the left side, three calendars and
Monday to Wednesday, and on the right side, Thursday to Sunday.  The default
layout has on the left side, three calendars and Monday, on the right side
Tuesday and Wednesday, then on the next two pages, Thursday and Friday, and
Saturday and Sunday.  In both layouts, the same day always appears in the same
position on the same page.

=item --weeks-after=I<N>

Ensure that the diary covers I<N> complete weeks after the specified year.

=item --weeks-before=I<N>

Ensure that the diary covers I<N> complete weeks before the specified year.

=item --year=I<year>

Print a diary for that year.  Defaults to next year.  If both B<--year> and
B<--start-date> are both specified, the last one specified will take
precedence.

=back

=head1 PCAL(1) F<.calendar> FILE

If B<makediary> finds a F<.calendar> file, it is parsed to find events to
print on particular days.  The file is in the same format as used by
pcal(1), with some extensions.

The F<.calendar> file is searched for in these places:

=over

=item * The file named by the environment variable B<DIARY_FILE>.

The file I<.calendar> in the directory named by the environment variable
B<DIARY_DIR>.

=item * The file I<.calendar> in the directory named by the environment
variable B<PCAL_DIR>.

=item * The file I<.calendar> in the current directory.

=item * The file I<.calendar> in the directory named by the environment
variable B<HOME>.

=back

The first one of these found is used, and the rest are ignored.

The I<.calendar> file allows a few extensions from that defined by pcal(1).
These extensions are embedded in comments, so the file should still make
sense to pcal(1).

The first type of extension allows for changing the behaviour of B<makediary>.  These
are of the form:

=over

B<<<< #<<I<key>:I<value>>> >>>>

=back

(This needs documentation...)

The second type of extension is similar in form, but is added to the end of the text for
a date entry.  The currently defined extensions are:

=over

=item B<<<< #<<image:F<filename>>> >>>>

Specify an image to print next to the entry for this event.  The image will
be scaled to fit in two lines of the diary.

=item B<<<< #<<year:I<year>>> >>>>

Specify the year in which the event occurred.  This is used so that the
text can contain a number of years since the event, in the %-substitution
extension format specified below.

=item B<<<< #<<warn:I<n>I<day(s)>|I<week(s)>|I<month(s)>>> >>>>

Print a warning in lighter text, I<n> days, weeks or months before the
event.  The text printed will be surrounded by parentheses and suffixed
by the date of the event, ie I<(Erin's 12th birthday -- Mar 07)>.

=back

=head2 %-Substitution

Within the extensions specified above, you can substitute some values with
B<%>-sequences.  The following sequences are available:

=over

=item B<%A>

Week day name (same as strftime(3)).

=item B<%a>

Abbreviated week day name (same as strftime(3)).

=item B<%B>

Full month name (same as strftime(3)).

=item B<%b>

Abbreviated month name (same as strftime(3)).

=item B<%d>

Day of month, 1 to 31.  If preceded by B<0>, ie B<%0d>, the month is printed as
01 to 31, same as strftime(3).

=item B<%j>

Day of year as decimal number (same as strftime(3)).  Three digits if B<%0j>.

=item B<%l>

Days remaining in the year.  Three digits if B<%0l>.

=item B<%m>

Month number, 01 to 12 (same as strftime(3)).

=item B<%N>

The number of years since the event.  If preceded by B<o>, ie B<%oN>, the
number will be printed as an ordinal, ie B<14th> instead of B<14>.

=item B<%U>

The week number of the current week (same as strftime(3)).

=item B<%Y>

Four digit year (same as strftime(3)).

=item B<%y>

Two digit year (same as strfimte(3)).

=item B<%%>

Literal %.

=back

=head2 Examples

=over

=item *

 1-1 Joe Bloggs' %oN birthday #<<image:joebloggs.jpg>> \
                              #<<year:1872>>

Print Joe's birthday, with a picture of Joe, and substitute his age, as an
ordinal.  In 2001, this will say "Joe Bloggs' 129th birthday".

=back

=head1 F<.makediaryrc> file

B<makediary> will read a file called F<.makediaryrc> if it exists.
F<.makediaryrc> must be in ini-file format, and it must contain a section
called "Personal Information".  The key-value pairs in that section are used to
populate the Personal Information page.  The defined keys are:

=over

=item Name

=item Phone

=item Mobile (or Cell)

=item Email (or Email address)

=item Address

=item Work phone

=item Work fax

=item Work address

=item Emergency Contact 1

=item Emergency Contact 2

=item Emergency Contact 3

=item Emergency Contact 4

=back

(It is intended that F<.makediaryrc> will one day hold all of the
information needed by B<makediary>, including that now kept in the
F<.calendar> file.)

=head1 EXAMPLES

=over

=item Two pages on letter paper

 makediary --page-size=half-letter | \
 psselect -p2- | \
 pstops -p letter '2:0L(8.5in,0)+1L(8.5in,5.5in)'  \
 > out.ps

=back

=head1 BUGS

The extensions to the F<.calendar> format are really ugly.  There should really
be a better way of specifying events etc.  The backward compatibility with
pcal(1) is not as useful as I imagined it would be.  Two ideas are to use a
simple database format (perhaps nosql(1)), or use the user's palm data,
exported from evolution(1) or somewhere.

=head1 AUTHOR

Russell Steicke <russells@adelie.cx>

=head1 COPYRIGHT

Copyright (C) 2002-2004 Russell Steicke.  Released under the terms of the GNU
General Public License, but dedicated to the public domain at the beginning of
the tenth calendar year after publishing (ie the start of 2019 for version 0.2.95).

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

=head1 VERSION

0.2.95

=head1 SEE ALSO

pcal(1), calendar(1), psselect(1), pstops(1).
