#!/bin/sh

# Create the python module distribution.  This must be run from within
# the makediary source directory.

set -e -x

# Check for things that indicat we are in the makediary source
# directory.
[ -f VERSION ]
[ -f PAPER.txt ]
[ -f setup.py ]
[ -d makediary ]

make man
make eps

rm -rf dist build MANIFEST

python setup.py sdist
python setup.py bdist

# RPM building is broken, it looks for makediary.1 where there is a
# makediary.1.gz.
# Fixed the man page problem, now it won't build when I include the embedded
# EPS pages.

#python setup.py bdist_rpm

