#!/bin/sh

# Create the python module distribution.  This must be run from within
# the makediary source directory.

# $Id: make-dists 73 2003-06-07 09:52:09Z  $

set -e -x

# Check for things that indicat we are in the makediary source
# directory.
[ -f VERSION ]
[ -f PAPER.txt ]
[ -f setup.py ]
[ -d makediary ]

_VERSION="$(head -1 VERSION)"

set +e
Changes="$( tla changes > /dev/null ; echo $? )"
set -e

case $Changes in
  0) Modified=""    ; break ;;
  1) Modified=" (Modified)" ; break ;;
  *)
    echo Error from '`tla changes`' 1>&2
    exit $Changes
    break ;;
esac

TlaVersion=$(tla tree-version)--$(tla logs | tail -1)"$Modified"

./make-man
rm -rf dist build MANIFEST

python setup.py sdist
python setup.py bdist

# RPM building is broken, it looks for makediary.1 where there is a
# makediary.1.gz.

#python setup.py bdist_rpm

