#!/bin/sh

# Make the debian package.  This must be run from within the source
# directory.

set -e -x

# Check for things that indicate we are in the makediary source
# directory.
[ -f VERSION ]
[ -f PAPER.txt ]
[ -f setup.py ]
[ -d makediary ]

_VERSION="$(head -1 VERSION)"

_SRC_DIR="$(pwd)"
_TMP_DIR=$_SRC_DIR/tmp
_DEB_BUILD_DIR=$_TMP_DIR/deb/makediary-$_VERSION

# These gymnastics are to ensure that the parent directory exists, but
# the directory itself does not.
rm -rf $_DEB_BUILD_DIR
mkdir -p $_DEB_BUILD_DIR

git ls-tree -z --name-only -r HEAD \
   | tar cf - -T - --null \
   | ( cd $_DEB_BUILD_DIR  &&  tar xvf - )

cd $_DEB_BUILD_DIR
./make-man

cd eps
./compile-unix-ref
./compile-sh-ref
cd vi-ref
./compile-vi-ref
./compile-vi-back
cd ../..

fakeroot dpkg-buildpackage -uc -us

cd $_SRC_DIR
mkdir -p dist-deb
cp -pv $_TMP_DIR/deb/makediary_* dist-deb/
