#!/bin/sh

# Create the EPS files.  This must be run from within
# the makediary source directory.

set -e -x

# Check for things that indicat we are in the makediary source
# directory.
[ -f VERSION ]
[ -f PAPER.txt ]
[ -f setup.py ]
[ -d makediary ]

for d in eps/* ; do
    if [ -d "$d" -a -f "$d"/compile -a -x "$d"/compile ] ; then
	echo Compiling EPS files in $d
	( cd "$d" && ./compile )
    fi
done

