#!/bin/bash

# Make the makediary man page.

# $Id: make-man 70 2003-01-13 17:24:07Z anonymous $


pod2man  --center="User Commands" \
         --release="User Commands" \
         man/makediary.pod \
         man/makediary.1

pod2html --header \
         --infile=man/makediary.pod \
         --outfile=man/makediary.1.html
