#!/bin/sh

set -e -x

_VERSION="$(head -1 VERSION)"
_URL="$( sed -n 's=^\$URL: \([^ ]*\).*$=\1=p' < VERSION )"

rm -rf dist build MANIFEST

python setup.py sdist
python2.2 setup.py bdist

# RPM building is broken, it looks for makediary.1 where there is a
# makediary.1.gz.

#python setup.py bdist_rpm

