#!/bin/sh

# Create the python module distribution.  This must be run from within
# the makediary source directory.

# $Id: make-dists 52 2002-12-31 17:41:50Z anonymous $

set -e -x

# Check for things that indicat we are in the makediary source
# directory.
[ -f VERSION ]
[ -f PAPER.txt ]
[ -f setup.py ]
[ -d makediary ]

_VERSION="$(head -1 VERSION)"
_URL="$( sed -n 's=^\$URL: \([^ ]*\).*$=\1=p' < VERSION )"

./make-man
rm -rf dist build MANIFEST

python setup.py sdist
python2.2 setup.py bdist

# RPM building is broken, it looks for makediary.1 where there is a
# makediary.1.gz.

#python setup.py bdist_rpm

