#!/bin/sh
set -e -x

rm -f awk.???.eps

(
    set -e -x
    cat awk-input-header.tex
    ../compile-1line.py < awk1line-input.txt
    cat awk-input-trailer.tex
) > awk.tex

latex awk.tex
dvips -E -i -o awk. awk.dvi
for z in awk.00? ; do
    mv $z $z.eps
done


