#!/bin/sh
if [ -z "$AWK" -o ! -x "$AWK" ] ; then
	if `which gawk >/dev/null 2>&1` ; then
		AWK=gawk
	else
		AWK=awk
	fi
fi
set -e -x
"$AWK" -f compile-conversions.awk < conversions-input.tex > conversions.tex
latex conversions.tex
test $(grep -c conformability conversions.tex) -eq 0
test $(grep -ci 'parse error' conversions.tex) -eq 0
dvips -E -o conversions.eps  conversions.dvi


