#!/bin/sh

# Copy the source tree to adelie.cx (scp.bur.st).

# $Id: export-cdp-to-burst 9 2002-12-22 07:31:21Z anonymous $

set -e

D=~/tmp/export-to-burst-$(date +%Y%m%d-%H%M%S)

mkdir -p $D
cd $D
wget -r http://localhost:10080/cdp/repos
cd localhost:10080/cdp
tar cf - repos | ssh shell.bur.st 'cd public_html/adelie.cx/cdp && tar xf -'

cd
rm -rf $D
