#!/bin/sh

set -e -x

rm -rf dist build MANIFEST

python setup.py sdist
python setup.py bdist

# RPM building is broken, it looks for makediary.1 where there is a
# makediary.1.gz.

#python setup.py bdist_rpm

