#!/bin/sh
if [ -z "$AWK" -o ! -x "$AWK" ] ; then
	if `which gawk >/dev/null 2>&1` ; then
		AWK=gawk
	else
		AWK=awk
	fi
fi
set -e -x
"$AWK" -f compile-units.awk < units-input.tex > units.tex
latex units.tex
test $(grep -c conformability units.tex) -eq 0
test $(grep -ci 'parse error' units.tex) -eq 0
dvips -E -o units.eps  units.dvi


